# Generated by Django 2.1.1 on 2018-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_id', models.IntegerField(max_length=8)),
                ('gender', models.IntegerField(max_length=1)),
                ('mobile_phone', models.CharField(max_length=64)),
            ],
        ),
    ]
