# Generated by Django 2.1.1 on 2018-10-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empnew',
            name='id',
        ),
        migrations.AlterField(
            model_name='empnew',
            name='emp_id',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
