# Generated by Django 2.1.1 on 2018-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0002_auto_20181015_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empnew',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empnew',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
