# Generated by Django 2.1.1 on 2018-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0004_auto_20181015_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empnew',
            name='emp_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='empnew',
            name='mobile_phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
