# Generated by Django 2.1.1 on 2018-10-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0005_auto_20181015_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=64, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.IntegerField(null=True)),
                ('addr', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
