# Generated by Django 2.1.1 on 2018-10-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0006_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empnew',
            table='empnew',
        ),
    ]
