# Generated by Django 2.1.1 on 2018-10-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0007_auto_20181015_0823'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
