# Generated by Django 2.1.1 on 2018-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0009_auto_20181016_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-createDate']},
        ),
        migrations.AddField(
            model_name='student',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
