# Generated by Django 2.1.1 on 2018-11-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0011_auto_20181017_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empnew',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='addr',
            field=models.CharField(max_length=64, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='createDate',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
