# Generated by Django 2.1.1 on 2018-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0012_auto_20181106_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
    ]
