# Generated by Django 2.1.1 on 2018-11-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodjango', '0013_auto_20181106_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=3, null=True, verbose_name='年龄')),
                ('sex', models.CharField(max_length=1, null=True, verbose_name='性别')),
                ('birthDay', models.DateField(verbose_name='生日')),
            ],
            options={
                'db_table': 'emp',
                'ordering': ['-age'],
            },
        ),
    ]
